version: 1
disable_existing_loggers: True

formatters:
  standard:
    format: '%(asctime)s.%(msecs)03d|%(process)d|%(levelno)s|%(module)s| - %(message)s'
    datefmt: '%Y%m%d%H%M%S'
  print:
    format: '%(asctime)s.%(msecs)03d | %(message)s'
    datefmt: '%Y%m%d%H%M%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: print
    stream: ext://sys.stdout
  file':
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: py-demo

root:
  level: NOTSET
  handlers: [console, file]